List<Map<String, dynamic>> languages = [
  {"code": "en", "label": "English"},
  {"code": "pt-br", "label": "Portuguese (Br)"},
  {"code": "ru", "label": "Russian"},
  {"code": "fr", "label": "French"},
  {"code": "es-la", "label": "Spanish (LATAM)"},
  {"code": "pl", "label": "Polish"},
  {"code": "tr", "label": "Turkish"},
  {"code": "it", "label": "Italian"},
  {"code": "es", "label": "Spanish (Es)"},
  {"code": "id", "label": "Indonesian"},
  {"code": "vi", "label": "Vietnamese"},
  {"code": "hu", "label": "Hungarian"},
  {"code": "zh", "label": "Chinese (Simp.)"},
  {"code": "ar", "label": "Arabic"},
  {"code": "de", "label": "German"},
  {"code": "zh-hk", "label": "Chinese (Trad.)"},
  {"code": "ca", "label": "Catalan"},
  {"code": "th", "label": "Thai"},
  {"code": "bg", "label": "Bulgarian"},
  {"code": "fa", "label": "Persian"},
  {"code": "uk", "label": "Ukrainian"},
  {"code": "mn", "label": "Mongolian"},
  {"code": "he", "label": "Hebrew"},
  {"code": "ro", "label": "Romanian"},
  {"code": "ms", "label": "Malay"},
  {"code": "tl", "label": "Tagalog"},
  {"code": "ja", "label": "Japanese"},
  {"code": "ko", "label": "Korean"},
  {"code": "hi", "label": "Hindi"},
  {"code": "my", "label": "Burmese"},
  {"code": "cs", "label": "Czech"},
  {"code": "pt", "label": "Portuguese (Pt)"},
  {"code": "nl", "label": "Dutch"},
  {"code": "sv", "label": "Swedish"},
  {"code": "bn", "label": "Bengali"},
  {"code": "no", "label": "Norwegian"},
  {"code": "lt", "label": "Lithuanian"},
  {"code": "el", "label": "Greek"},
  {"code": "sr", "label": "Serbo-Croatian"},
  {"code": "da", "label": "Danish"},
  {"code": "fi", "label": "Finnish"},
  {"code": "NULL", "label": "Other"},
];
